export const CONFIG = {
    VALERION_GEN: 124,
    SPRITE_PATH: 'sprites/'
};

export const TYPE_MAP = {
    NORMAL: { esp: 'Normal', color: '#A8A77A' },
    FIRE: { esp: 'Fuego', color: '#EE8130' },
    WATER: { esp: 'Agua', color: '#6390F0' },
    GRASS: { esp: 'Planta', color: '#7AC74C' },
    ELECTRIC: { esp: 'Eléctrico', color: '#F7D02C' },
    ICE: { esp: 'Hielo', color: '#96D9D6' },
    FIGHTING: { esp: 'Lucha', color: '#C22E28' },
    POISON: { esp: 'Veneno', color: '#A33EA1' },
    GROUND: { esp: 'Tierra', color: '#E2BF65' },
    FLYING: { esp: 'Volador', color: '#A98FF3' },
    PSYCHIC: { esp: 'Psíquico', color: '#F95587' },
    BUG: { esp: 'Bicho', color: '#A6B91A' },
    ROCK: { esp: 'Roca', color: '#B6A136' },
    GHOST: { esp: 'Fantasma', color: '#735797' },
    DRAGON: { esp: 'Dragón', color: '#6F35FC' },
    STEEL: { esp: 'Acero', color: '#B7B7CE' },
    DARK: { esp: 'Siniestro', color: '#705746' },
    FAIRY: { esp: 'Hada', color: '#D685AD' },
    QMARKS: { esp: 'Desconocido', color: '#555' }
};

// js/config.js

// ... (CONFIG y TYPE_MAP se quedan igual)

export const ABILITY_MAP = {
    "OVERGROW": "Espesura",
    "BLAZE": "Mar Llamas",
    "TORRENT": "Torrente",
    "SHIELDDUST": "Polvo Escudo",
    "STATIC": "Elec. Estática",
    "INTIMIDATE": "Intimidación",
    "GUTS": "Agallas",
    "STURDY": "Robustez",
    "DRIZZLE": "Llovizna",
    "DROUGHT": "Sequía",
    "SPEEDBOOST": "Impulso",
    "BATTLEARMOR": "Armadura Batalla",
    "DAMP": "Humedad",
    "LIMBER": "Flexibilidad",
    "SANDVEIL": "Velo Arena",
    "VOLTABSORB": "Absorbe Elec.",
    "WATERABSORB": "Absorbe Agua",
    "OBLIVIOUS": "Despiste",
    "CLOUDNINE": "Aclimatación",
    "COMPOUNDEYES": "Ojocompuesto",
    "INSOMNIA": "Insomnio",
    "COLORCHANGE": "Cambio Color",
    "IMMUNITY": "Inmunidad",
    "FLASHFIRE": "Absorbe Fuego",
    "OWNTEMPO": "Ritmo Propio",
    "SUCTIONCUPS": "Ventosas",
    "SHADOWTAG": "Sombratrampa",
    "ARENATRAP": "Trampa Arena",
    "ROUGHSKIN": "Piel Tosca",
    "WONDERGUARD": "Superguarda",
    "LEVITATE": "Levitación",
    "EFFECTSPORE": "Efecto Espora",
    "SYNCHRONIZE": "Sincronía",
    "CLEARBODY": "Cuerpo Puro",
    "NATURALCURE": "Cura Natural",
    "LIGHTNINGROD": "Pararrayos",
    "SERENEGRACE": "Dicha",
    "SWIFTSWIM": "Nado Rápido",
    "CHLOROPHYLL": "Clorofila",
    "ILLUMINATE": "Iluminación",
    "TRACE": "Rastro",
    "HUGEPOWER": "Potencia",
    "POISONPOINT": "Punto Tóxico",
    "INNERFOCUS": "Foco Interno",
    "MAGMAARMOR": "Escudo Magma",
    "WATERVEIL": "Velo Agua",
    "MAGNETPULL": "Imán",
    "SOUNDPROOF": "Insonorizar",
    "RAINDISH": "Cura Lluvia",
    "SANDSTREAM": "Chorro Arena",
    "PRESSURE": "Presión",
    "THICKFAT": "Sebo",
    "EARLYBIRD": "Madrugar",
    "FLAMEBODY": "Cuerpo Llama",
    "RUNAWAY": "Fuga",
    "KEENEYE": "Vista Lince",
    "HYPERCUTTER": "Corte Fuerte",
    "PICKUP": "Recogida",
    "TRUANT": "Ausente",
    "HUSTLE": "Entusiasmo",
    "CUTECHARM": "Gran Encanto",
    "PLUS": "Más",
    "MINUS": "Menos",
    "FORECAST": "Predicción",
    "STICKYHOLD": "Viscosidad",
    "SHEDSKIN": "Mudar",
    "PUREPOWER": "Energía Pura",
    "SHELLARMOR": "Caparazón",
    "AIRLOCK": "Bucle Aire",
    "TANGLEDFEET": "Tumbos",
    "MOTORDRIVE": "Electromotor",
    "RIVALRY": "Rivalidad",
    "STEADFAST": "Impasible",
    "SNOWCLOAK": "Manto Níveo",
    "GLUTTONY": "Gula",
    "ANGERPOINT": "Irascible",
    "UNBURDEN": "Liviano",
    "HEATPROOF": "Ignífugo",
    "SIMPLE": "Ignorante",
    "DRYSKIN": "Piel Seca",
    "DOWNLOAD": "Descarga",
    "IRONFIST": "Puño Férreo",
    "POISONHEAL": "Antídoto",
    "ADAPTABILITY": "Adaptable",
    "SKILLLINK": "Encadenado",
    "HYDRATION": "Hidratación",
    "SOLARPOWER": "Poder Solar",
    "QUICKFEET": "Pies Rápidos",
    "NORMALIZE": "Normalidad",
    "SNIPER": "Francotirador",
    "MAGICGUARD": "Muro Mágico",
    "NOGUARD": "Indefenso",
    "STALL": "Rezagado",
    "TECHNICIAN": "Experto",
    "LEAFGUARD": "Defensa Hoja",
    "KLUTZ": "Zoquete",
    "MOLDBREAKER": "Rompemoldes",
    "SUPERLUCK": "Afortunado",
    "AFTERMATH": "Resquicio",
    "ANTICIPATION": "Anticipación",
    "FOREWARN": "Alerta",
    "UNAWARE": "Ignorante",
    "TINTEDLENS": "Cromolente",
    "FILTER": "Filtro",
    "SLOWSTART": "Inicio Lento",
    "SCRAPPY": "Intrépido",
    "STORMDRAIN": "Colector",
    "ICEBODY": "Gélido",
    "SOLIDROCK": "Roca Sólida",
    "SNOWWARNING": "Nevada",
    "HONEYGATHER": "Recogemiel",
    "FRISK": "Cacheo",
    "RECKLESS": "Audaz",
    "MULTITYPE": "Multitipo",
    "FLOWERGIFT": "Don Floral",
    "BADDREAMS": "Mal Sueño",
    "PICKPOCKET": "Hurto",
    "SHEERFORCE": "Potencia Bruta",
    "CONTRARY": "Respondón",
    "UNNERVE": "Nerviosismo",
    "DEFIANT": "Competitivo",
    "DEFEATIST": "Flaqueza",
    "CURSEDBODY": "Cuerpo Maldito",
    "HEALER": "Alma Cura",
    "FRIENDGUARD": "Compiescolta",
    "WEAKARMOR": "Armadura Frágil",
    "HEAVYMETAL": "Met. Pesado",
    "LIGHTMETAL": "Met. Liviano",
    "MULTISCALE": "Multiescala",
    "TOXICBOOST": "Ímpetu Tóxico",
    "FLAREBOOST": "Ímpetu Ardiente",
    "HARVEST": "Cosecha",
    "TELEPATHY": "Telepatía",
    "MOXIE": "Autoestima",
    "OVERCOAT": "Funda",
    "POISONTOUCH": "Toque Tóxico",
    "REGENERATOR": "Regeneración",
    "BIGPECKS": "Sacapecho",
    "SANDRUSH": "Ímpetu Arena",
    "WONDERSKIN": "Piel Milagro",
    "ANALYTIC": "Cálculo Final",
    "ILLUSION": "Ilusión",
    "IMPOSTER": "Impostor",
    "INFILTRATOR": "Allanamiento",
    "MUMMY": "Momia",
    "JUSTIFIED": "Justiciero",
    "RATTLED": "Cobardía",
    "MAGICBOUNCE": "Espejo Mágico",
    "SAPSIPPER": "Herbívoro",
    "PRANKSTER": "Bromista",
    "SANDFORCE": "Poder Arena",
    "IRONBARBS": "Punta Acero",
    "ZENMODE": "Modo Daruma",
    "VICTORYSTAR": "Tinovictoria",
    "TURBOBLAZE": "Turbollama",
    "TERAVOLT": "Terravoltaje",
    "AERILATE": "Piel Celeste",
    "AROMAVEIL": "Velo Aroma",
    "AURABREAK": "Rompeaura",
    "BULLETPROOF": "Antibalas",
    "CHEEKPOUCH": "Carrillo",
    "COMPETITIVE": "Tenacidad",
    "DARKAURA": "Aura Oscura",
    "DELTASTREAM": "Ráfaga Delta",
    "FAIRYAURA": "Aura Feérica",
    "FLOWERVEIL": "Velo Flor",
    "FURCOAT": "Pelaje Recio",
    "GALEWINGS": "Alas Vendaval",
    "GOOEY": "Viscosidad",
    "GRASSPELT": "Manto Frondoso",
    "MAGICIAN": "Prestidigitador",
    "MEGALAUNCHER": "Megadisparador",
    "PARENTALBOND": "Amor Filial",
    "PIXILATE": "Piel Feérica",
    "REFRIGERATE": "Piel Helada",
    "STANCECHANGE": "Cambio Táctico",
    "STRONGJAW": "Mandíbula Fuerte",
    "SWEETVEIL": "Velo Dulce",
    "SYMBIOSIS": "Simbiosis",
    "TOUGHCLAWS": "Garra Dura",
    "BERSERK": "Cólera",
    "DAZZLING": "Cuerpo Vívido",
    "DISGUISE": "Disfraz",
    "ELECTRICSURGE": "Electrogénesis",
    "FLUFFY": "Peluche",
    "FULLMETALBODY": "Guardia Metálica",
    "GALVANIZE": "Piel Eléctrica",
    "GRASSYSURGE": "Herbogénesis",
    "INNARDSOUT": "Revés",
    "LIQUIDVOICE": "Voz Fluida",
    "LONGREACH": "Remoto",
    "MERCILESS": "Ensañamiento",
    "MISTYSURGE": "Nebulogénesis",
    "POWERCONSTRUCT": "Agrupamiento",
    "PRISMARMOR": "Armadura Prisma",
    "PSYCHICSURGE": "Psicogénesis",
    "QUEENLYMAJESTY": "Regia Presencia",
    "RKSSYSTEM": "Sistema Alfa",
    "RECEIVER": "Receptor",
    "SCHOOLING": "Banco",
    "SHADOWSHIELD": "Guardia Espectro",
    "SHIELDSDOWN": "Escudo Limitado",
    "SLUSHRUSH": "Quitanieves",
    "STAMINA": "Firmeza",
    "STEELWORKER": "Acero Templado",
    "SURGESURFER": "Cola Surf",
    "TANGLINGHAIR": "Rizo Rebelde",
    "TRIAGE": "Primer Auxilio",
    "WATERBUBBLE": "Pompa",
    "WATERCOMPACTION": "Hidrorrefuerzo",
    "WIMPOUT": "Huida",
    "LIBERO": "Líbero",
    "STEAMENGINE": "Combustible",
    "PALEOSYNTHESIS": "Paleosíntesis",
    "QUARKDRIVE": "Carga Cuark",
    "ORICHALCUMPULSE": "Latido Oricalco",
    "HADRONENGINE": "Motor Hadrónico",
    "OPPORTUNIST": "Oportunista",
    "CUDBIEW": "Rumia",
    "EARTHEATER": "Terra-absorción",
    "GUARDDOG": "Perro Guardián",
    "MYCELIUMMIGHT": "Poder Micológico",
    "SHARPNESS": "Agudeza",
    "SUPREMEOVERLORD": "General Supremo",
    "THERMALEXCHANGE": "Termoconversión",
    "TOXICDEBRIS": "Residuos Tóxicos",
    "WELLBAKEDBODY": "Cuerpo Horneado",
    "WINDPOWER": "Energía Eólica",
    "WINDRIDER": "Surcavientos",
    "ZEROTOHERO": "Cambio Heroico",
    "ARMORTAIL": "Cola Armadura",
    "ANGERSHELL": "Coraza Ira"
};